#default job properties
EVENTS_SOURCE_PATH=data/raw/dataset.json
PROCESSED_REGISTERED_EVENTS_PATH=/data/processed/registered
PROCESSED_APPLOADED_EVENTS_PATH=/data/processed/app_loaded
SPARK_MASTER=local[*]